name: Reax pipeline

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:runner-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.5"
    - name: Set up Python
      run: uv python install 3.10.15
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Test with pytest
      run: uv run -n pytest

  lint:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v4
          with:
            version: "0.5.5"
        - name: Set up Python
          run: uv python install 3.10.15
        - name: Install the project
          run: uv sync --only-dev
        - name: Install hooks and run pre-commit
          run: |
            uv run pre-commit install-hooks &&
            uv run pre-commit run --all-files
